Repository huskyroboticsteam/Scarlet, pull requests merged in 2018-04, with the labels that each got.

#16 PWM and I2C Additions
  Components/Outputs/PCA9685.cs
  Components/Outputs/RGBLED.cs
  Components/PCA9685.cs
  IO/BeagleBone/I2CBusBBB.cs
  IO/BeagleBone/PWMDeviceBBB.cs
  IO/II2CBus.cs
  IO/IPWMOutput.cs
  IO/RaspberryPi/I2CBusPi.cs
  IO/RaspberryPi/RaspberryPi.cs
  Scarlet.csproj
  Utilities/UtilData.cs
Labels: devices, enhancement, hardware-io

#17 Adding INA226 Sensor
  Components/Sensors/INA226.cs
  Scarlet.csproj
Labels: enhancement, sensor

#18 Data log changes
  UnitTest/UtilitiesTesting/DataLogTesting.cs
  Utilities/DataLog.cs
Labels: bug, enhancement

#19 Adding Test Suite
  IO/BeagleBone/PWMDeviceBBB.cs
  Scarlet.sln
  TestSuite/App.config
  TestSuite/IOBBB.cs
  TestSuite/IOPi.cs
  TestSuite/Main.cs
  TestSuite/Performance.cs
  TestSuite/Properties/AssemblyInfo.cs
  TestSuite/TestSuite.csproj
  TestSuite/TestSuite.csproj.user
  TestSuite/Utils.cs
Labels: enhancement

#14 A couple fixes
  Components/Motors/TalonMC.cs
  Components/Sensors/Potentiometer.cs
  Controllers/PID.cs
Labels: bug, motors
