Repository huskyroboticsteam/Scarlet, pull requests merged in 2018-06, with the labels that each got.

#31 CAN and VESC Edits
  Components/Motors/VESC.cs
  Components/Sensors/MTK3339.cs
  IO/BeagleBone/BBBPinManager.cs
  IO/BeagleBone/CANBusBBB.cs
Labels: enhancement, hardware-io

#34 LS7366R Beta Implementation
  Components/Sensors/LS7366R.cs
  Scarlet.csproj
Labels: devices, enhancement

#33 GPS Fix
  Components/Sensors/MTK3339.cs
Labels: bug, sensor

#43 Adding SetDelay(float) to IPWMOutput
  IO/BeagleBone/PWMDeviceBBB.cs
  IO/IPWMOutput.cs
  UnitTest/MotorTesting/TestablePWMOutput.cs
Labels: enhancement, hardware-io

#44 BME280 Environmental Sensor Implementation
  Components/Sensors/BME280.cs
  Scarlet.csproj
  UnitTest/ComponentTesting/BME280Tests.cs
  UnitTest/UnitTest.csproj
Labels: devices, enhancement, sensor

#46 PCA9685 Output Polarity
  Components/Outputs/PCA9685.cs
Labels: bug, devices, enhancement, hardware-io, motors

#49 Trace Logging
  Components/IMotor.cs
  Components/ISensor.cs
  Components/ISubsystem.cs
  Components/Motors/CytronMD30C.cs
  Components/Motors/Servo.cs
  Components/Motors/TalonMC.cs
  Components/Motors/VESC.cs
  Components/Outputs/PCA9685.cs
  Components/Sensors/BME280.cs
  Components/Sensors/BNO055.cs
  Components/Sensors/INA226.cs
  Components/Sensors/LS7366R.cs
  Components/Sensors/LimitSwitch.cs
  Components/Sensors/MAX31855.cs
  Components/Sensors/MPU6050.cs
  Components/Sensors/MTK3339.cs
  Components/Sensors/Potentiometer.cs
  Components/Sensors/VEML6070.cs
  Components/Sensors/VH400.cs
  Utilities/Log.cs
Labels: enhancement

#47 MQ135 Air Pollutant Sensor Implementation
  Components/Sensors/MQ135.cs
  Scarlet.csproj
Labels: devices, enhancement, sensor

#51 RPi I/O Thread Safety
  IO/RaspberryPi/I2CBusPi.cs
  IO/RaspberryPi/SPIBusPi.cs
Labels: bug, enhancement, hardware-io

#45 Implementation of TLV2544
  Components/Inputs/TLV2544.cs
  Scarlet.csproj
Labels: devices, enhancement, hardware-io

#56 Filter update
  Filters/Average.cs
  Filters/Filter.cs
  Filters/LowPass.cs
  UnitTest/FilterTesting/TestAverage.cs
  UnitTest/FilterTesting/TestLowPass.cs
  UnitTest/UnitTest.csproj
Labels: enhancement, filters
